### PR TITLE
update bindings to support node 14

### PR DESCRIPTION
**Pull request by Benjaminrivard**
Hello,

In response to PR #12, I tried to update the faulty bindings.

I ran `make test` and `make big-test`, both turned to be OK 24/24.

Let me know I can be of any help,

Best, Benjamin

### CODE REVIEW

**Comment by jimkang** [comment]
I looked it over, and it looks good. (And I verified that the test pass over here as well.) Thanks a ton for taking on finding out what the API changes were and working on adapting the wrapper!

It looks like this PR is marked as in-progress. Do you have any other changes planned?

**Comment by Benjaminrivard** [comment]
Dear Jim,

I was doing some additional testing on my end! Thank you for your review, and for maintaining the lib :smile: 

Best, Benjamin

**Comment by jimkang** [comment]
Cool! Merging!

**Review by jimkang — APPROVED** [review]

**Comment by jimkang** [comment]
All right. I added you to the contributor list, these changes have been published in 3.0.3.

**Pull request merged**
